// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    lrSidebar: [{ type: 'autogenerated', dirName: '.' }],
    hrSidebar: [{ type: 'autogenerated', dirName: '.' }],
    mrSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;